package com.fantamomo.slack.approver.model

enum class RequestDecisionReason {
    USER_VERIFIED,
    USER_UNVERIFIED,
    USER_UNVERIFIED_ALLOWED_SCOPES,
    ENTERPRISE_INSTALL,
    RESTRICTED_SCOPE,
    PREVIOUSLY_DENIED,
    RESTRICTED_APPLICATION,
    MANUAL_REVIEW,
    MANUAL_OVERRIDE,
    USER_WITHDRAWN,
    USER_REQUESTED_REVIEW,
    RESOLUTION_UNDONE
}